PACKAGE_NAME = Argentum 

include $(GNUSTEP_MAKEFILES)/common.make

BUNDLE_NAME = Argentum
BUNDLE_EXTENSION = .theme

$(BUNDLE_NAME)_INSTALL_DIR = $(GNUSTEP_LIBRARY)/Themes

$(BUNDLE_NAME)_RESOURCE_FILES = \
	Resources/Info-gnustep.plist \
	Resources/ThemeImages \
	Resources/ThemeTiles \
	Resources/*.clr

include $(GNUSTEP_MAKEFILES)/bundle.make
